#ifndef CONSTANT_H
#define CONSTANT_H

#define MAGIC_NUM 1314522
#define TEST_BLOCKSIZE 4096
#define TEST_N_BLOCKS 10
#define TEST_INODE_TABLE_START_IDX 4
#define TEST_ROOT_INODE_NUM 0
#define TEST_FILENAME_MAX_LEN 256
#define RESERVE_BLOCKS 2 //dummy and sb

#endif
